export const SET_INITIAL_BOARD = "BOARD/SET_INITIAL_BOARD";
export const SET_BOARD = "BOARD/SET_BOARD";
export const SET_INPUT_BOARD = "BOARD/SET_INPUT_BOARD";
export const SET_LOADING = "LOADING/SET_LOADING";
export const SET_STATUS = "STATUS/SET_STATUS";
export const SET_LEADERBOARD = "LEADERBOARD/SET_LEADERBOARD";
